### ISSUE TITLE
UI improvement - links are visible by default

### ISSUE THREAD

**Issue by feranto** [lgmorand/aks-checklist#143]
When the checklist is loaded by default, all links to the documentation are collapsed. Some users have reported that they didn't realize the links were there:

![ui1](https://user-images.githubusercontent.com/561920/80509876-f982be80-8947-11ea-8061-4b887288b73b.png)

It would be better to have all the links expanded by default so they can see that the links are there:

![ui2](https://user-images.githubusercontent.com/561920/80510079-3bac0000-8948-11ea-8fa7-dfcbf12690c3.png)

It is no intuitive that if they click in the arrow of each item, it will expand and show the docs. Feedback received from multiple users.

**Comment by lgmorand** [comment]
It tooks me quite a time to get it work. new colors for icons, new tooltips but also a dynamic tooltip the first few seconds of the page
![UI tooltip](https://user-images.githubusercontent.com/6757079/80543664-b4927280-89af-11ea-8245-24640d83924c.png)

I'll merge it with my next PR to master
