### ISSUE TITLE
Add: Any specific checks for AKS Windows Clusters 

### ISSUE THREAD

**Issue by geoffreygeslin** [lgmorand/aks-checklist#147]
I just found your aks-checklist site and want to thank you.
This is a great tool for those (like me) who are new to AKS/Kubernetes...

As Windows Containers Support in AKS just turned to General Availability today ([see announcement](https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-windows-server-containers-and-private-clusters-for-azure-kubernetes-service/)), I'm wondering if some specific checks should apply to Windows AKS clusters and Windows containers ?
If so, could the "aks-checklist" could reflect it?

As of today, I do not have specific checks to suggest, but some toughts about these points :
- I saw Kubernetes supports specific properties for Windows app deployments (in yaml file)... maybe there are some best-practive to list about it.
- Also, there is still today a kind of tight coupling between host-OS and container OS on Windows Containers (do not know if an action prior deployment could mitigate the risk of a container break after an host-OS update on the AKS platform...)

Geoffrey

**Comment by lgmorand** [comment]
@geoffreygeslin that's a very good point!

I think there are some best practices
- Reboot windows nodes for patching => Kured does not work for Windows nodes => I don't know what it the solution
- Know the limitations of WinNodes, for instance, no network policy, so ensuring another layer of security may be necessary
- indeed the fact that the docker base image much match the operating system version

If you feel confident, don't hesitate to contribute with a PR :)

**Comment by geoffreygeslin** [comment]
Thank you @lgmorand.

I'll consider contributing aks-cheklist.
At least, if I found new Windows specific best-practice, I'll add a comment here.

**Comment by lgmorand** [comment]
@geoffreygeslin I keep open, as an idea to implement ;-)

**Comment by lgmorand** [comment]
@geoffreygeslin here you are: https://stoakscheckliststaging.z16.web.core.windows.net/#section-windows

still on staging, please have a look

**Comment by geoffreygeslin** [comment]
@lgmorand Nice ! Thank you for this work, this can save a lot of time wandering in documentations...

I'll contribute if I notice another missing Windows specific check.
