### ISSUE TITLE
Cluster Setup - Security

### ISSUE THREAD

**Issue by fduran** [lgmorand/aks-checklist#248]
In the `Check if you need the Kubernetes dashboard:` item, it follows:

`By default Kubernetes deploys and exposed the default dashboard.`

This should perhaps read:  `By default Kubernetes in AKS deploys and exposes the default dashboard for clusters running a Kubernetes version less than 1.18.` 

Source: https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard

**Comment by lgmorand** [comment]
will be solve in my next push. Thanks Fernando
