### ISSUE TITLE
Translation to portuguese

### ISSUE THREAD

**Issue by Guilhermeslucas** [lgmorand/aks-checklist#262]
I was wondering if portuguese is a language you need some help with the support. I would be happy to help!

**Comment by lgmorand** [comment]
it's a community initiative. If you think portugese version could be useful for portugese/brazilian people, feel free to translate :)

BUT I'll say that the hardest part is to keep the portugese version up to date with main (english). So you can start but for instance, spanish is quite behind already and the guy who did it does not have a lot of time to maintain it right now.

the time passing, I'm not sure localizing was a good idea at first, even if I started it with french :D

**Comment by lgmorand** [comment]
I finally disabled langages. too hard to maintain all translations at the same level of completeness. I prefer to stick to english finally
