### ISSUE TITLE
AKS checklist still points to Kube-advisor, deprecated tool

### ISSUE THREAD

**Issue by msftnadavbh** [lgmorand/aks-checklist#271]
The cluster maintenance section still points to Kube-advisor,
a tool no-longer in active development -

https://github.com/Azure/kube-advisor

Under cluster maintenance -

![image](https://user-images.githubusercontent.com/29725442/117330981-f1385a00-ae9e-11eb-90c9-7c10bd2ff7e1.png)

**Comment by lgmorand** [comment]
@msftnadavbh thanks. we are planning to update the list of tools listed in the list. it's sad that we, MS, stopped the dev of kubeadvisor :)
