### ISSUE TITLE
I believe this description is wrong

### ISSUE THREAD

**Issue by nc-ruth** [lgmorand/aks-checklist#279]
https://github.com/lgmorand/aks-checklist/blob/91f696e096df00e1d8cae583fbbf5f06fbe99b91/data/en/items/cluster_setup.json#L87

I just saw that it's a duplicate entry of the description above.

**Comment by lgmorand** [comment]
@nc-ruth probably :) thanks for the PR. I'm in holidays but I'll fix all of them when coming back
